### ISSUE TITLE
Sleep Issue

### ISSUE THREAD

**Issue by ciancrobbo** [ghayyem/acer_swift_5_1065g7#3]
Doesn't look like this has been updated in a little while. Did you ever get sleep to work or have any workaround suggestions? I've tried a few things but no luck!

**Comment by 1757791488** [comment]
合盖睡眠问题可以通过一款小软件解决，教程我已经发在公众号：菜鸟搞机，或者B站搜“吃瓜市民王先生”进行学习

**Comment by 1757791488** [comment]
小舒服，目前小完美，😄

**Comment by ciancrobbo** [comment]
I don't speak Chinese and the translation seems very wrong. Any chance you could translate to English for me?

**Comment by ghayyem** [comment]
Hi, I don't have the laptop anymore to test it out.
have you tried  igfxonln=1
